// SPDX-License-Identifier: AGPL-3.0-only

//! Background remote-sync worker for the web server (issue #129).
//!
//! When the operator configures a sync account and an encrypted key file, this
//! module spawns a dedicated OS thread that drives
//! [`pergamon_sync::run_forever`]: it opens its **own** `SQLite` connection to the
//! same database file (WAL mode makes cross-connection writes safe, so a
//! network-bound sync round never holds the request-handler mutex), builds the
//! ADR-024 crypto context from the shared [`pergamon_keystore`], and runs
//! repeated push+pull rounds on an interval with exponential backoff on
//! offline/transient failures.
//!
//! The returned [`pergamon_sync::SyncControl`] lets request handlers trigger an
//! out-of-band round (`POST /admin/sync-remote/trigger`) and lets `main` stop
//! the worker on shutdown.

use std::path::PathBuf;
use std::sync::{
    Arc,
    atomic::{AtomicBool, Ordering},
};
use std::time::Duration;

use anyhow::{Context, Result, anyhow, bail};
use pergamon_storage::Database;
use pergamon_sync::{SyncError, Transport};

/// Observable lifecycle of a real authenticated sync worker.
pub enum WorkerEvent {
    /// A round is in progress; configuration alone is not success.
    Syncing,
    /// Push, pull and upload-completeness verification all succeeded.
    Synced(pergamon_sync::SyncStats),
    /// Retryable failure with the actual scheduled delay.
    Offline(String, u64),
    /// Fatal failure, with a separate re-login classification.
    Failed(String, bool),
    /// The worker has terminated.
    Stopped,
}

/// Owned control and thread termination, so reconfiguration cannot overlap workers.
pub struct WorkerHandle {
    control: pergamon_sync::SyncControl,
    stopping: Arc<AtomicBool>,
    thread: Option<std::thread::JoinHandle<()>>,
}

impl WorkerHandle {
    /// Queue a round, without claiming it completed.
    pub fn trigger(&self) -> bool {
        self.control.trigger()
    }

    /// Stop between transport calls and join the owned worker.
    pub fn stop(&mut self) -> Result<()> {
        self.stopping.store(true, Ordering::Release);
        let _ = self.control.shutdown();
        if let Some(thread) = self.thread.take() {
            thread.join().map_err(|_| anyhow!("sync worker panicked"))?;
        }
        Ok(())
    }
}

impl Drop for WorkerHandle {
    fn drop(&mut self) {
        if let Err(error) = self.stop() {
            tracing::error!(error=%error, "sync worker shutdown failed");
        }
    }
}

/// Validated content authority supplied by the local onboarding service.
pub struct AuthenticatedWorkerConfig {
    /// Canonical database, opened independently of request handlers.
    pub db_path: PathBuf,
    /// Durable plaintext blob directory.
    pub blob_dir: PathBuf,
    /// Validated relay destination.
    pub server: String,
    /// Canonical content ID, never the auth tenant.
    pub content_id: pergamon_crypto::AccountId,
    /// Existing root key; never generated by worker startup.
    pub ark: pergamon_crypto::AccountRootKey,
    /// Local device private keys.
    pub keys: pergamon_crypto::DeviceKeypairs,
    /// Active epoch from local storage.
    pub epoch: u32,
    /// Shared, durably rotating provider for all relay surfaces.
    pub provider: Arc<dyn pergamon_sync::credential::AccessTokenProvider>,
    /// Healthy sync cadence.
    pub interval_secs: u64,
    /// Nonsecret lifecycle observer.
    pub observe: Arc<dyn Fn(WorkerEvent) + Send + Sync>,
}

struct Interruptible<T> {
    transport: T,
    stopping: Arc<AtomicBool>,
}

impl<T> Interruptible<T> {
    fn check(&self) -> pergamon_sync::error::Result<()> {
        if self.stopping.load(Ordering::Acquire) {
            Err(SyncError::NotEnabled("worker stopping".into()))
        } else {
            Ok(())
        }
    }
}

impl<T: Transport> Transport for Interruptible<T> {
    fn push(
        &self,
        request: &pergamon_sync::wire::PushRequest,
    ) -> pergamon_sync::error::Result<pergamon_sync::wire::PushResponse> {
        self.check()?;
        self.transport.push(request)
    }
    fn pull(
        &self,
        account: &str,
        after: u64,
        limit: Option<u32>,
    ) -> pergamon_sync::error::Result<pergamon_sync::wire::PullResponse> {
        self.check()?;
        self.transport.pull(account, after, limit)
    }
    fn blob_probe(
        &self,
        request: &pergamon_sync::wire::BlobProbeRequest,
    ) -> pergamon_sync::error::Result<pergamon_sync::wire::BlobProbeResponse> {
        self.check()?;
        self.transport.blob_probe(request)
    }
    fn blob_put(
        &self,
        account: &str,
        hash: &str,
        bytes: &[u8],
    ) -> pergamon_sync::error::Result<()> {
        self.check()?;
        self.transport.blob_put(account, hash, bytes)
    }
    fn blob_get(&self, account: &str, hash: &str) -> pergamon_sync::error::Result<Vec<u8>> {
        self.check()?;
        self.transport.blob_get(account, hash)
    }
}

/// Start a real authenticated worker; the caller has already committed adoption.
pub fn spawn_authenticated(config: AuthenticatedWorkerConfig) -> Result<WorkerHandle> {
    let db = Database::open(&config.db_path)?;
    let binding = db
        .remote_account_binding()?
        .ok_or_else(|| anyhow!("authenticated binding missing"))?;
    let state = db.sync_state()?;
    if binding.state != "active"
        || binding.content_account_id != config.content_id.to_hex()
        || binding.relay_url != config.server
        || binding.device_id != config.keys.device_id()
        || state.account_id.as_deref() != Some(binding.content_account_id.as_str())
        || state.device_id.as_deref() != Some(config.keys.device_id())
    {
        bail!("worker identity does not match active authenticated binding");
    }
    let transport = pergamon_sync::http::HttpTransport::new(&config.server)?
        .with_token_provider(config.provider.clone());
    let relay = pergamon_sync::HttpRelay::new(&config.server)?.with_token_provider(config.provider);
    let crypto = pergamon_sync::CryptoContext::new(
        config.ark,
        config.content_id.to_hex(),
        config.keys.device_id().into(),
        *config.keys.ed25519_signing(),
        config.epoch,
    )?;
    let blobs = pergamon_sync::FsBlobStore::new(&config.blob_dir).map_err(|e| anyhow!(e))?;
    let stopping = Arc::new(AtomicBool::new(false));
    let transport = Interruptible {
        transport,
        stopping: stopping.clone(),
    };
    let mut engine =
        pergamon_sync::SyncEngine::new(transport, crypto, pergamon_sync::DeviceKeyDirectory::new());
    let scheduler = pergamon_sync::SyncScheduler::new(
        Duration::from_secs(config.interval_secs.max(1)),
        pergamon_sync::BackoffPolicy::new(BACKOFF_BASE, BACKOFF_MAX, BACKOFF_MULTIPLIER),
    );
    let (control, sleeper) = pergamon_sync::control();
    let stop = stopping.clone();
    let thread = std::thread::Builder::new()
        .name("pergamon-sync-worker".into())
        .spawn(move || {
            let result = pergamon_sync::run_forever(
                || {
                    engine.transport().check()?;
                    (config.observe)(WorkerEvent::Syncing);
                    let roster = pergamon_sync::onboarding::roster(&relay, &config.content_id)?;
                    engine.update_device_directory(pergamon_sync::DeviceKeyDirectory::from_roster(
                        &roster,
                    ));
                    let counters = engine.sync(&db, &blobs)?;
                    engine.verify_upload_complete(&db)?;
                    Ok(counters)
                },
                scheduler,
                &sleeper,
                pergamon_sync::Jitter::from_entropy(),
                |report| match &report.outcome {
                    pergamon_sync::RoundOutcome::Synced(counters) => {
                        (config.observe)(WorkerEvent::Synced(*counters));
                    }
                    pergamon_sync::RoundOutcome::Offline(message) => (config.observe)(
                        WorkerEvent::Offline(message.clone(), report.next_delay.as_secs()),
                    ),
                },
            );
            if let Err(error) = result
                && !stop.load(Ordering::Acquire)
            {
                let login = matches!(
                    error,
                    SyncError::AuthRefused { status: 401, .. }
                        | SyncError::SessionNeedsLogin { .. }
                );
                let message = crate::onboarding::public_error(&anyhow::Error::new(error));
                tracing::error!(error=%message, "authenticated sync worker stopped");
                (config.observe)(WorkerEvent::Failed(message, login));
            } else {
                (config.observe)(WorkerEvent::Stopped);
            }
        })?;
    Ok(WorkerHandle {
        control,
        stopping,
        thread: Some(thread),
    })
}

/// Operator-supplied configuration for the background sync worker.
pub struct SyncWorkerConfig {
    /// Path to the `SQLite` database file (the worker opens its own connection).
    pub db_path: PathBuf,
    /// Account handle whose keys back this sync (as stored in the key file).
    pub account: String,
    /// Path to the Argon2id-encrypted key file holding the account root key.
    pub key_file: PathBuf,
    /// Passphrase that unlocks the key file.
    pub passphrase: String,
    /// Seconds between successful sync rounds.
    pub interval_secs: u64,
}

/// Base backoff delay after the first offline/transient failure.
const BACKOFF_BASE: Duration = Duration::from_secs(5);
/// Ceiling the backoff delay is clamped to (5 minutes).
#[allow(clippy::duration_suboptimal_units)]
const BACKOFF_MAX: Duration = Duration::from_secs(300);
/// Backoff growth factor per consecutive failure.
const BACKOFF_MULTIPLIER: f64 = 2.0;

/// Read the sync transport credential from the environment (issue #183).
///
/// Mirrors the CLI's precedence so a server whose background worker syncs
/// through an authenticating reverse proxy can supply the same credential:
/// 1. `PERGAMON_SYNC_BEARER_TOKEN` (non-empty) → bearer token.
/// 2. `PERGAMON_SYNC_BASIC_USER` + `PERGAMON_SYNC_BASIC_PASSWORD` → HTTP Basic.
/// 3. otherwise `None` (unauthenticated).
///
/// The credential is read only from the environment and is never logged.
fn sync_credential_from_env() -> Option<pergamon_sync::TransportCredential> {
    if let Ok(token) = std::env::var("PERGAMON_SYNC_BEARER_TOKEN")
        && !token.is_empty()
    {
        return Some(pergamon_sync::TransportCredential::Bearer { token });
    }
    match (
        std::env::var("PERGAMON_SYNC_BASIC_USER"),
        std::env::var("PERGAMON_SYNC_BASIC_PASSWORD"),
    ) {
        (Ok(username), Ok(password)) if !username.is_empty() => {
            Some(pergamon_sync::TransportCredential::Basic { username, password })
        }
        _ => None,
    }
}

/// Start the background sync worker, returning a control handle.
///
/// # Errors
/// Returns an error if remote sync is not enabled on the database, if the key
/// file cannot be unlocked, or if the crypto/transport context cannot be built.
#[allow(clippy::too_many_lines)]
pub fn spawn(config: SyncWorkerConfig) -> Result<WorkerHandle> {
    let SyncWorkerConfig {
        db_path,
        account,
        key_file,
        passphrase,
        interval_secs,
    } = config;

    // A dedicated connection: the worker must not contend with request handlers
    // for the shared `AppState` mutex during network I/O.
    let db = Database::open(&db_path)
        .with_context(|| format!("opening sync-worker database at {}", db_path.display()))?;

    let state = db.sync_state().context("reading sync state")?;
    if db.remote_account_binding()?.is_some() {
        bail!(
            "authenticated binding requires the secure session worker; no environment or blind fallback"
        );
    }
    let Some(server) = state.server_url.clone() else {
        bail!(
            "remote sync is not enabled on this database; run \
             `pergamon sync-remote enable --server <url>` first"
        );
    };
    let account_hex = state
        .account_id
        .clone()
        .ok_or_else(|| anyhow!("sync identity is incomplete (no account id)"))?;
    let device_id = state
        .device_id
        .clone()
        .ok_or_else(|| anyhow!("sync identity is incomplete (no device id)"))?;

    let store = pergamon_keystore::DeviceKeyStore::encrypted_file(
        key_file.clone(),
        zeroize::Zeroizing::new(passphrase).as_bytes(),
    )
    .with_context(|| format!("unlocking key file {}", key_file.display()))?;
    let ark = store
        .load_ark(&account)?
        .ok_or_else(|| anyhow!("no account root key for '{account}' in the key file"))?;
    let keys = store
        .load_device_keys(&account)?
        .ok_or_else(|| anyhow!("no device key for '{account}' in the key file"))?;
    let signing_key = *keys.ed25519_signing();

    let crypto = pergamon_sync::CryptoContext::new(
        ark,
        account_hex,
        device_id,
        signing_key,
        state.key_epoch,
    )
    .context("building crypto context")?;
    let transport = pergamon_sync::http::HttpTransport::with_credential(
        server.clone(),
        sync_credential_from_env(),
    )
    .context("building HTTP transport")?;
    // Verify pulled events against the account roster (ADR-030). Best-effort:
    // an empty directory still lets push and single-device pull proceed, while
    // an unknown multi-device signer surfaces as a retryable `UnknownSigner`.
    let directory = load_device_directory(&store, &account, &server);
    let stopping = Arc::new(AtomicBool::new(false));
    let engine = pergamon_sync::SyncEngine::new(
        Interruptible {
            transport,
            stopping: stopping.clone(),
        },
        crypto,
        directory,
    );
    let blobs = pergamon_sync::FsBlobStore::new(
        db_path
            .parent()
            .unwrap_or_else(|| std::path::Path::new("."))
            .join("blobs"),
    )
    .map_err(|e| anyhow!(e))?;

    let interval = Duration::from_secs(interval_secs.max(1));
    let backoff = pergamon_sync::BackoffPolicy::new(BACKOFF_BASE, BACKOFF_MAX, BACKOFF_MULTIPLIER);
    let scheduler = pergamon_sync::SyncScheduler::new(interval, backoff);
    let (control, sleeper) = pergamon_sync::control();

    let thread = std::thread::Builder::new()
        .name("pergamon-sync-worker".to_owned())
        .spawn(move || {
            let result = pergamon_sync::run_forever(
                || engine.sync(&db, &blobs),
                scheduler,
                &sleeper,
                pergamon_sync::Jitter::from_entropy(),
                log_round,
            );
            match result {
                Ok(()) => tracing::info!("background sync worker stopped"),
                Err(e) => tracing::error!("background sync worker stopped on fatal error: {e}"),
            }
        })
        .context("spawning sync worker thread")?;

    tracing::info!(
        server = %server,
        interval_secs,
        "background sync worker started"
    );
    Ok(WorkerHandle {
        control,
        stopping,
        thread: Some(thread),
    })
}

/// Fetch the account roster over the relay and project it into a
/// [`pergamon_sync::DeviceKeyDirectory`] for pulled-event signature verification
/// (ADR-030). Returns an empty directory (logging a warning) on any failure, so
/// push and single-device pull still run.
fn load_device_directory(
    store: &pergamon_keystore::DeviceKeyStore,
    account: &str,
    server: &str,
) -> pergamon_sync::DeviceKeyDirectory {
    let build = || -> Result<pergamon_sync::DeviceKeyDirectory> {
        let account_id = store
            .load_account_id(account)?
            .ok_or_else(|| anyhow!("no account id for '{account}' in the key file"))?;
        let relay = pergamon_sync::HttpRelay::with_credential(
            server.to_owned(),
            sync_credential_from_env(),
        )
        .context("building relay client")?;
        let roster = pergamon_sync::onboarding::roster(&relay, &account_id)
            .context("listing device roster")?;
        Ok(pergamon_sync::DeviceKeyDirectory::from_roster(&roster))
    };
    build().unwrap_or_else(|e| {
        tracing::warn!("could not load device roster for signature verification: {e:#}");
        pergamon_sync::DeviceKeyDirectory::new()
    })
}

/// Log the result of one background sync round.
fn log_round(report: &pergamon_sync::RoundReport) {
    match &report.outcome {
        pergamon_sync::RoundOutcome::Synced(stats) => {
            if stats.pushed > 0 || stats.applied > 0 {
                tracing::info!(
                    pushed = stats.pushed,
                    applied = stats.applied,
                    next_secs = report.next_delay.as_secs(),
                    "sync round complete"
                );
            } else {
                tracing::debug!(
                    next_secs = report.next_delay.as_secs(),
                    "sync round complete (no changes)"
                );
            }
        }
        pergamon_sync::RoundOutcome::Offline(msg) => {
            tracing::warn!(
                consecutive_failures = report.consecutive_failures,
                retry_secs = report.next_delay.as_secs(),
                "sync round offline: {msg}"
            );
        }
    }
}
